version: '3.9'
services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  api-gateway:
    build: .
    image: ecommerce-api-gateway:latest
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/api_gateway
      - REDIS_URL=redis://redis:6379
      - ADMIN_API_KEYS=change-me-admin-key
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redis
volumes:
  mongo_data: